//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookfrizApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cjenik
    {
        public int idCjenik { get; set; }
        public int idUsluga { get; set; }
        public int idSalon { get; set; }
    
        public virtual Salon Salon { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
