//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaPodataka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI2230_DBEntities : DbContext
    {
        public PI2230_DBEntities()
            : base("name=PI2230_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akcija> Akcijas { get; set; }
        public virtual DbSet<Cjenik> Cjeniks { get; set; }
        public virtual DbSet<Grad> Grads { get; set; }
        public virtual DbSet<Klijent> Klijents { get; set; }
        public virtual DbSet<Recenzija> Recenzijas { get; set; }
        public virtual DbSet<Salon> Salons { get; set; }
        public virtual DbSet<Termin> Termins { get; set; }
        public virtual DbSet<Usluga> Uslugas { get; set; }
        public virtual DbSet<Vlasnik> Vlasniks { get; set; }
    }
}
