//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzija
    {
        public int IdRecenzija { get; set; }
        public string Opis { get; set; }
        public Nullable<int> Ocjena { get; set; }
        public Nullable<int> IdTermin { get; set; }
    
        public virtual Termin Termin { get; set; }
    }
}
