//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msitaric
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akcija
    {
        public int IdAkcija { get; set; }
        public string OpisAkcije { get; set; }
        public string VrijemeTrajanja { get; set; }
        public double NovaCijena { get; set; }
        public int IdCjenik { get; set; }
    
        public virtual Cjenik Cjenik { get; set; }
    }
}
