//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msitaric
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cjenik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cjenik()
        {
            this.Akcija = new HashSet<Akcija>();
        }
    
        public int idCjenik { get; set; }
        public int idUsluga { get; set; }
        public int idSalon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akcija> Akcija { get; set; }
        public virtual Salon Salon { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
