//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msitaric
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI2230_DBEntities : DbContext
    {
        public PI2230_DBEntities()
            : base("name=PI2230_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akcija> Akcija { get; set; }
        public virtual DbSet<Cjenik> Cjenik { get; set; }
        public virtual DbSet<Klijent> Klijent { get; set; }
        public virtual DbSet<Recenzija> Recenzija { get; set; }
        public virtual DbSet<Salon> Salon { get; set; }
        public virtual DbSet<Termin> Termin { get; set; }
        public virtual DbSet<Usluga> Usluga { get; set; }
    }
}
