//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msitaric
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termin()
        {
            this.Recenzija = new HashSet<Recenzija>();
        }
    
        public int idTermin { get; set; }
        public System.TimeSpan Vrijeme { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<int> IdKlijent { get; set; }
        public int IdSalon { get; set; }
    
        public virtual Klijent Klijent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzija> Recenzija { get; set; }
        public virtual Salon Salon { get; set; }
        public virtual Termin Termin1 { get; set; }
        public virtual Termin Termin2 { get; set; }
    }
}
