//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavijesti
    {
        public int id_klijenta { get; set; }
        public Nullable<int> sve_obavijesti { get; set; }
        public Nullable<int> obavijesti_jedan_dan_prije { get; set; }
        public Nullable<int> obavijesti_jedan_sat_prije { get; set; }
        public Nullable<int> bez_obavijesti { get; set; }
    
        public virtual Klijent Klijent { get; set; }
    }
}
